-- Supabase SQL Editor에 복사해서 실행하세요.
-- 1. members 테이블 생성
CREATE TABLE public.members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT UNIQUE NOT NULL,
    phone TEXT,
    password TEXT NOT NULL,
    marketing TEXT DEFAULT '동의 (이메일)',
    status TEXT DEFAULT '정상',
    "joinDate" TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. 외부 API에서 접근할 수 있도록 보안 정책(RLS) 해제 (테스트용)
-- 상용화 전에는 정책을 세부적으로 설정해야 하지만, 현재는 백엔드 서버가 DB를 제어하므로 RLS를 끕니다.
ALTER TABLE public.members DISABLE ROW LEVEL SECURITY;

-- 3. site_settings 테이블 생성
CREATE TABLE public.site_settings (
    id INT PRIMARY KEY,
    settings_data JSONB,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 외부 API 접근 허용
ALTER TABLE public.site_settings DISABLE ROW LEVEL SECURITY;

-- 4. products 테이블 생성
CREATE TABLE public.products (
    id INT PRIMARY KEY,
    product_data JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 외부 API 접근 허용
ALTER TABLE public.products DISABLE ROW LEVEL SECURITY;
